from __future__ import annotations

import re
from typing import Any


"""
Validator for generated MetaStock Explorer JSON.

Scope:
- This validator is deliberately conservative.
- It checks generated Explorer code fields, not trading correctness.
- It should allow functions that exist in the current knowledge base, while
  still catching common LLM mistakes such as natural-language formulas,
  undefined ColX references, programming operators, and future references.

Important:
- The generator prompt already says explorer_code_body may use direct formulas.
- ColA/ColB references are allowed in explorer_code_body only when the matching
  column is defined.
- Historical references should be placed inside column formulas, not around ColA.
"""


# Registry-enabled function cards currently known in the project knowledge base.
# Keep this broad enough for retrieval/generation as the KB expands.
ALLOWED_FUNCTIONS = {
    # Core project MVP functions
    "RSI",
    "Mov",
    "Cross",
    "Ref",
    "HHV",
    "LLV",
    "MACD",
    "If",
    "Abs",
    "Sum",
    "ROC",
    "ATR",
    "Max",
    "Min",
    "Cum",
    "ValueWhen",
    "BarsSince",
    "LastValue",

    # Expanded knowledge-base functions
    "ADX",
    "Alert",
    "AroonDown",
    "AroonUp",
    "ATAN",
    "BBandBot",
    "BBandTop",
    "Cos",
    "Divergence",
    "Fml",
    "FmlVar",
    "Input",
    "MDI",
    "PDI",
    "Peak",
    "PeakBars",
    "RVI",
    "Security",
    "Sin",
    "Sqrt",
    "Stdev",
    "Stoch",
    "StochMomentum",
    "Trough",
    "TroughBars",
    "Typical",
    "Var",
    "Wilders",
    "WillR",
    "WriteIf",
    "WriteVal",
    "Zig",
}

# Functions that may exist in MetaStock but are usually not suitable for a
# normal Explorer scan generated by this project. These are currently retained
# as metadata and are not treated as hard validation errors.
CAUTION_FUNCTIONS = {
    "Alert": (
        "Alert is usually an Expert Advisor / alert-style helper. "
        "Confirm it is intended for Explorer."
    ),
    "Input": (
        "Input prompts are Indicator Builder-specific in normal usage. "
        "Prefer fixed constants for Explorer."
    ),
    "WriteIf": (
        "WriteIf is commentary-oriented and should not normally appear "
        "in Explorer filters."
    ),
    "WriteVal": (
        "WriteVal is commentary-oriented and should not normally appear "
        "in Explorer filters."
    ),
    "Zig": (
        "ZigZag-style functions can repaint. "
        "Use only when the query explicitly asks for them."
    ),
    "Peak": (
        "Peak/Trough functions can depend on ZigZag-style swing logic. "
        "Check repaint/lookahead assumptions."
    ),
    "PeakBars": (
        "Peak/Trough functions can depend on ZigZag-style swing logic. "
        "Check repaint/lookahead assumptions."
    ),
    "Trough": (
        "Peak/Trough functions can depend on ZigZag-style swing logic. "
        "Check repaint/lookahead assumptions."
    ),
    "TroughBars": (
        "Peak/Trough functions can depend on ZigZag-style swing logic. "
        "Check repaint/lookahead assumptions."
    ),
    "Security": (
        "Security references external instruments. "
        "Confirm the target symbol/source is explicit."
    ),
    "Fml": (
        "Fml references an external custom indicator. "
        "Confirm that the referenced indicator exists in MetaStock."
    ),
    "FmlVar": (
        "FmlVar references an external custom indicator variable. "
        "Confirm that the referenced indicator exists."
    ),
}

VALID_COL_LETTERS = set("ABCDEFGHIJKL")

PROGRAMMING_OPERATOR_ERRORS = {
    "==": "Use = instead of ==.",
    "&&": "Use AND instead of &&.",
    "||": "Use OR instead of ||.",
}

# Natural-language field names are valid in MetaStock in some contexts, but the
# project standard is to emit abbreviated fields. Treat exact words as errors
# only when they appear as standalone formula tokens.
NATURAL_LANGUAGE_FIELD_REPLACEMENTS = {
    "close": "Use C instead of close inside generated formulas.",
    "volume": "Use V instead of volume inside generated formulas.",
    "open": "Use O instead of open inside generated formulas.",
    "high": "Use H instead of high inside generated formulas.",
    "low": "Use L instead of low inside generated formulas.",
}

SYSTEM_TESTER_ONLY_PATTERNS = [
    (
        re.compile(r"\bOPT\d+\b", re.IGNORECASE),
        "OPT variables are System Tester-only. "
        "Use fixed constants in Explorer.",
    ),
    (
        re.compile(r"\bSimulation\.", re.IGNORECASE),
        "Simulation.* functions are System Tester-only and should not be "
        "used in Explorer.",
    ),
]


def check_parentheses(text: str) -> list[str]:
    errors: list[str] = []
    stack: list[int] = []

    for i, char in enumerate(text):
        if char == "(":
            stack.append(i)
        elif char == ")":
            if not stack:
                errors.append(
                    f"Unmatched closing parenthesis at position {i}."
                )
            else:
                stack.pop()

    if stack:
        errors.append("Unmatched opening parenthesis.")

    return errors


def strip_string_literals(formula: str) -> str:
    """
    Remove quoted strings before token checks.

    This prevents false positives on formulas such as:
        Fml("My Close Indicator")
    """
    return re.sub(r'"[^"]*"', '""', formula)


def extract_functions(formula: str) -> list[str]:
    formula_without_strings = strip_string_literals(formula)

    return re.findall(
        r"\b([A-Za-z][A-Za-z0-9_]*)\s*\(",
        formula_without_strings,
    )


def extract_col_references(formula: str) -> set[str]:
    return {
        match.upper()
        for match in re.findall(
            r"\bCol([A-L])\b",
            formula,
            flags=re.IGNORECASE,
        )
    }


def contains_ref_of_col(formula: str) -> bool:
    return bool(
        re.search(
            r"\bRef\s*\(\s*Col[A-L]\s*,",
            formula,
            flags=re.IGNORECASE,
        )
    )


def extract_ref_calls(formula: str) -> list[str]:
    """
    Return the argument bodies of every balanced Ref(...) call.

    Nested Ref calls are returned independently.

    Examples:
        Ref(LLV(C,20),-2)
        -> ["LLV(C,20),-2"]

        Ref(Ref(C,-1),1)
        -> ["Ref(C,-1),1", "C,-1"]
    """
    calls: list[str] = []

    for match in re.finditer(
        r"\bRef\s*\(",
        formula,
        flags=re.IGNORECASE,
    ):
        open_parenthesis = formula.find("(", match.start())

        if open_parenthesis == -1:
            continue

        depth = 1
        cursor = open_parenthesis + 1

        while cursor < len(formula) and depth > 0:
            char = formula[cursor]

            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1

            cursor += 1

        if depth == 0:
            call_body = formula[
                open_parenthesis + 1:cursor - 1
            ]
            calls.append(call_body)

    return calls


def split_top_level_args(arg_text: str) -> list[str]:
    """
    Split a function argument list while preserving nested expressions.

    Example:
        "HHV(H,20),-1"
        -> ["HHV(H,20)", "-1"]
    """
    args: list[str] = []
    start = 0
    depth = 0

    for i, char in enumerate(arg_text):
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == "," and depth == 0:
            args.append(arg_text[start:i].strip())
            start = i + 1

    args.append(arg_text[start:].strip())

    return args


def validate_ref_lookahead(formula: str) -> list[str]:
    """
    Validate literal Ref() offsets without confusing nested function arguments
    for the Ref offset.

    Allowed:
        Ref(C,-1)
        Ref(HHV(H,20),-1)
        Ref(Mov(V,30,S),-1)
        Ref(C,0)
        Ref(C,+0)

    Rejected:
        Ref(C,1)
        Ref(C,+1)
        Ref(HHV(H,20),2)
        Ref(HHV(H,20),+2)
    """
    errors: list[str] = []

    for call_body in extract_ref_calls(formula):
        args = split_top_level_args(call_body)

        if len(args) != 2:
            errors.append(
                "Ref() should have exactly 2 arguments, "
                f"got: Ref({call_body})"
            )
            continue

        offset_text = args[1].strip()

        # Only literal integers greater than zero indicate definite lookahead.
        #
        # These are positive:
        #   1
        #   +1
        #   20
        #   +20
        #
        # These are allowed:
        #   -1
        #   -20
        #   0
        #   +0
        if re.fullmatch(r"\+?[1-9]\d*", offset_text):
            errors.append(
                f"Positive Ref offset {offset_text} references future data. "
                "Use negative offsets such as Ref(C,-1) for previous bars "
                "in Explorer."
            )

    return errors


def contains_positive_ref(formula: str) -> bool:
    """
    Return True when a Ref() call contains a literal positive offset.

    This compatibility helper now uses balanced-parentheses parsing rather
    than a flat regular expression. Nested expressions such as
    Ref(HHV(H,20),-1) therefore do not produce false positives.
    """
    return bool(validate_ref_lookahead(formula))


def validate_formula(
    formula: str,
    *,
    field_name: str = "formula",
    allow_col_references: bool = True,
) -> list[str]:
    errors: list[str] = []

    if not formula or not formula.strip():
        errors.append("Formula is empty.")
        return errors

    formula = formula.strip()
    formula_without_strings = strip_string_literals(formula)
    lower_formula = formula_without_strings.lower()

    errors.extend(check_parentheses(formula))

    for token, message in PROGRAMMING_OPERATOR_ERRORS.items():
        if token in lower_formula:
            errors.append(message)

    for pattern, message in SYSTEM_TESTER_ONLY_PATTERNS:
        if pattern.search(formula_without_strings):
            errors.append(message)

    if "filter:" in lower_formula:
        errors.append(
            "Do not include the label 'Filter:' in code fields."
        )

    if re.search(
        r"\bcol\s+[A-L]\s*=",
        formula_without_strings,
        re.IGNORECASE,
    ):
        errors.append(
            "Do not include 'col A =' inside col_code. "
            "Store only the formula body."
        )

    if re.search(
        r"\bcolumn\s+[A-L]\s*:",
        formula_without_strings,
        re.IGNORECASE,
    ):
        errors.append(
            "Do not include 'Column A:' labels inside code fields. "
            "Store only the formula body."
        )

    for natural_name, message in (
        NATURAL_LANGUAGE_FIELD_REPLACEMENTS.items()
    ):
        if re.search(
            rf"\b{re.escape(natural_name)}\b",
            lower_formula,
        ):
            errors.append(message)

    if contains_ref_of_col(formula_without_strings):
        errors.append(
            "Do not use Ref(ColA,-1) or other historical references on "
            "Explorer columns. Put Ref() inside a column formula instead."
        )

    # Balanced Ref() parsing replaces the old flat regex check.
    errors.extend(
        validate_ref_lookahead(formula_without_strings)
    )

    if (
        not allow_col_references
        and extract_col_references(formula_without_strings)
    ):
        errors.append(
            f"{field_name} should not reference "
            "ColA/ColB-style Explorer columns."
        )

    allowed_lower = {
        function_name.lower()
        for function_name in ALLOWED_FUNCTIONS
    }

    for function_name in extract_functions(
        formula_without_strings
    ):
        if function_name.lower() not in allowed_lower:
            errors.append(
                "Function may be unsupported or missing from whitelist: "
                f"{function_name}"
            )

    return errors


def validate_explorer_output(
    output: dict[str, Any],
) -> list[str]:
    errors: list[str] = []

    if not isinstance(output, dict):
        return [
            "Explorer output must be a JSON object / Python dict."
        ]

    explorer_name = str(
        output.get("explorer_name", "")
    ).strip()

    explorer_code_body = str(
        output.get("explorer_code_body", "")
    ).strip()

    col_definitions = output.get(
        "col_definitions",
        [],
    )

    if not explorer_name:
        errors.append("explorer_name is required.")

    if not explorer_code_body:
        errors.append("explorer_code_body is required.")

    if not isinstance(col_definitions, list):
        errors.append("col_definitions must be a list.")
        col_definitions = []

    defined_letters: set[str] = set()
    seen_letters: set[str] = set()

    for i, col in enumerate(col_definitions):
        if not isinstance(col, dict):
            errors.append(
                f"col_definitions[{i}] must be an object."
            )
            continue

        col_letter = str(
            col.get("col_letter", "")
        ).strip().upper()

        if col_letter not in VALID_COL_LETTERS:
            errors.append(
                f"col_definitions[{i}].col_letter must be one "
                f"of A-L, got {col_letter!r}."
            )
            continue

        if col_letter in seen_letters:
            errors.append(
                f"Duplicate col_letter: {col_letter}."
            )

        seen_letters.add(col_letter)
        defined_letters.add(col_letter)

    # Validate the Explorer filter after collecting defined columns.
    for error in validate_formula(
        explorer_code_body,
        field_name="explorer_code_body",
        allow_col_references=True,
    ):
        errors.append(
            f"explorer_code_body: {error}"
        )

    referenced_letters = extract_col_references(
        explorer_code_body
    )

    for letter in sorted(referenced_letters):
        if letter not in defined_letters:
            errors.append(
                f"explorer_code_body references Col{letter}, "
                f"but Column {letter} is not defined."
            )

    # Columns should normally be sequential because the automator/database
    # layer maps them into fixed MetaStock column slots.
    if defined_letters:
        ordered = sorted(defined_letters)
        expected = list(
            "ABCDEFGHIJKL"[:len(ordered)]
        )

        if ordered != expected:
            errors.append(
                "Column letters should be sequential from A "
                "where possible. "
                f"Got {ordered}, expected {expected}."
            )

    for i, col in enumerate(col_definitions):
        if not isinstance(col, dict):
            continue

        col_letter = str(
            col.get("col_letter", "")
        ).strip().upper()

        col_code = str(
            col.get("col_code", "")
        ).strip()

        if not col_code:
            errors.append(
                f"col_definitions[{i}].col_code is required."
            )
            continue

        for error in validate_formula(
            col_code,
            field_name=f"col {col_letter}",
            allow_col_references=False,
        ):
            errors.append(
                f"col {col_letter}: {error}"
            )

    return errors