BEGIN;


-- ============================================================
-- CONVERSATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.conversations (
    conversation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    title text,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    archived_at timestamptz,

    CONSTRAINT conversations_title_not_blank
        CHECK (
            title IS NULL
            OR btrim(title) <> ''
        )
);

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at
    ON public.conversations(updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversations_active_updated_at
    ON public.conversations(updated_at DESC)
    WHERE archived_at IS NULL;


-- ============================================================
-- LANGCHAIN-COMPATIBLE COMPLETED MESSAGE HISTORY
-- ============================================================

CREATE TABLE IF NOT EXISTS public.chat_history (
    id serial PRIMARY KEY,

    session_id uuid NOT NULL
        REFERENCES public.conversations(conversation_id)
        ON DELETE CASCADE,

    message jsonb NOT NULL,

    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_history_session_id
    ON public.chat_history(session_id);

CREATE INDEX IF NOT EXISTS idx_chat_history_session_order
    ON public.chat_history(session_id, id);
    

-- ============================================================
-- IN-PROGRESS / PARTIAL TURN STATE
-- ============================================================

CREATE TABLE IF NOT EXISTS public.turn_streams (
    stream_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    conversation_id uuid NOT NULL
        REFERENCES public.conversations(conversation_id)
        ON DELETE CASCADE,

    -- Generated by the UI or application service to prevent
    -- duplicate turn creation after retries.
    client_turn_id uuid NOT NULL,

    status text NOT NULL DEFAULT 'streaming',

    -- The completed HumanMessage and AIMessage are eventually
    -- copied into chat_history. During generation, the partial
    -- content lives here.
    user_content text NOT NULL,
    assistant_content text NOT NULL DEFAULT '',

    -- Monotonically increasing sequence for persisted chunks.
    last_sequence bigint NOT NULL DEFAULT 0,

    error_code text,
    error_message text,

    started_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,

    CONSTRAINT turn_streams_unique_client_turn
        UNIQUE (conversation_id, client_turn_id),

    CONSTRAINT turn_streams_valid_status
        CHECK (
            status IN (
                'streaming',
                'completed',
                'failed',
                'cancelled'
            )
        ),

    CONSTRAINT turn_streams_user_content_not_blank
        CHECK (btrim(user_content) <> ''),

    CONSTRAINT turn_streams_sequence_non_negative
        CHECK (last_sequence >= 0),

    CONSTRAINT turn_streams_completed_timestamp
        CHECK (
            status <> 'completed'
            OR completed_at IS NOT NULL
        )
);

CREATE INDEX IF NOT EXISTS idx_turn_streams_conversation
    ON public.turn_streams(
        conversation_id,
        started_at DESC
    );

CREATE INDEX IF NOT EXISTS idx_turn_streams_active
    ON public.turn_streams(
        conversation_id,
        started_at DESC
    )
    WHERE status = 'streaming';


-- ============================================================
-- TOOL-CALL HISTORY FOR UI AND AUDIT
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tool_calls (
    tool_call_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    conversation_id uuid NOT NULL
        REFERENCES public.conversations(conversation_id)
        ON DELETE CASCADE,

    stream_id uuid NOT NULL
        REFERENCES public.turn_streams(stream_id)
        ON DELETE CASCADE,

    -- Tool-call IDs supplied by an LLM provider are not
    -- guaranteed to be UUIDs.
    provider_call_id text,

    ordinal integer NOT NULL DEFAULT 0,

    tool_name text NOT NULL,
    status text NOT NULL DEFAULT 'running',

    arguments_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    result_json jsonb,

    error_code text,
    error_message text,

    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,

    CONSTRAINT tool_calls_unique_turn_ordinal
        UNIQUE (stream_id, ordinal),

    CONSTRAINT tool_calls_valid_status
        CHECK (
            status IN (
                'running',
                'succeeded',
                'failed',
                'cancelled'
            )
        ),

    CONSTRAINT tool_calls_name_not_blank
        CHECK (btrim(tool_name) <> ''),

    CONSTRAINT tool_calls_ordinal_non_negative
        CHECK (ordinal >= 0),

    CONSTRAINT tool_calls_finished_timestamp
        CHECK (
            status = 'running'
            OR finished_at IS NOT NULL
        )
);

CREATE INDEX IF NOT EXISTS idx_tool_calls_conversation
    ON public.tool_calls(
        conversation_id,
        started_at
    );

CREATE INDEX IF NOT EXISTS idx_tool_calls_stream
    ON public.tool_calls(
        stream_id,
        ordinal
    );


-- ============================================================
-- UPDATED-AT TRIGGERS
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_conversations_updated_at
    ON public.conversations;

CREATE TRIGGER trg_conversations_updated_at
BEFORE UPDATE ON public.conversations
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();


DROP TRIGGER IF EXISTS trg_turn_streams_updated_at
    ON public.turn_streams;

CREATE TRIGGER trg_turn_streams_updated_at
BEFORE UPDATE ON public.turn_streams
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();


-- ============================================================
-- UPDATE CONVERSATION ACTIVITY
-- ============================================================

CREATE OR REPLACE FUNCTION
public.touch_conversation_from_chat_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.conversations
    SET updated_at = now()
    WHERE conversation_id = NEW.session_id;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_conversation_on_message
    ON public.chat_history;

CREATE TRIGGER trg_touch_conversation_on_message
AFTER INSERT ON public.chat_history
FOR EACH ROW
EXECUTE FUNCTION
public.touch_conversation_from_chat_history();


CREATE OR REPLACE FUNCTION
public.touch_conversation_from_turn_stream()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.conversations
    SET updated_at = now()
    WHERE conversation_id = NEW.conversation_id;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_conversation_on_stream_start
    ON public.turn_streams;

CREATE TRIGGER trg_touch_conversation_on_stream_start
AFTER INSERT ON public.turn_streams
FOR EACH ROW
EXECUTE FUNCTION
public.touch_conversation_from_turn_stream();


DROP TRIGGER IF EXISTS trg_touch_conversation_on_stream_status
    ON public.turn_streams;

CREATE TRIGGER trg_touch_conversation_on_stream_status
AFTER UPDATE OF status ON public.turn_streams
FOR EACH ROW
WHEN (OLD.status IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION
public.touch_conversation_from_turn_stream();


-- ============================================================
-- API ACCESS RESTRICTION
-- ============================================================

ALTER TABLE public.conversations
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.chat_history
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.turn_streams
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tool_calls
    ENABLE ROW LEVEL SECURITY;

-- The desktop backend connects through trusted PostgreSQL
-- credentials. No browser/API role receives access yet.

REVOKE ALL ON TABLE public.conversations
    FROM anon, authenticated;

REVOKE ALL ON TABLE public.chat_history
    FROM anon, authenticated;

REVOKE ALL ON TABLE public.turn_streams
    FROM anon, authenticated;

REVOKE ALL ON TABLE public.tool_calls
    FROM anon, authenticated;

REVOKE ALL ON SEQUENCE public.chat_history_id_seq
    FROM anon, authenticated;


COMMIT;